load("@crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")
load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_test")

rust_binary(
    name = "control-plane",
    srcs = glob(["src/*.rs"]),
    aliases = aliases(),
    crate_name = "xscope_control_plane",
    crate_root = "src/main.rs",
    edition = crate_edition(),
    proc_macro_deps = all_crate_deps(proc_macro = True),
    visibility = ["//visibility:public"],
    deps = [
        "//rust/crates/domain",
        "//rust/crates/entities",
        "//rust/crates/migration",
        "//rust/crates/payments",
        "//rust/crates/telemetry",
    ] + all_crate_deps(normal = True),
)

rust_test(
    name = "control_plane_test",
    crate = ":control-plane",
    deps = all_crate_deps(normal_dev = True),
)
