apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: xscope-system
resources:
  - resources.yaml
configMapGenerator:
  - name: xscope-serving-envoy
    files: [envoy.yaml]
  - name: xscope-serving-epp
    files: [plugins.yaml, plugins-vllm.yaml]
