load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "platform",
    srcs = ["platform.go"],
    importpath = "xscope.dev/xscope/control-plane/internal/platform",
    visibility = ["//go/control-plane:__subpackages__"],
    deps = ["@com_github_go_playground_validator_v10//:validator"],
)

go_test(
    name = "platform_test",
    srcs = ["platform_test.go"],
    embed = [":platform"],
)
