load("@crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "telemetry",
    srcs = glob(["src/*.rs"]),
    crate_name = "xscope_telemetry",
    aliases = aliases(),
    edition = crate_edition(),
    proc_macro_deps = all_crate_deps(proc_macro = True),
    deps = all_crate_deps(normal = True),
    visibility = ["//visibility:public"],
)

rust_test(name = "telemetry_test", crate = ":telemetry")
