load("@rules_rust//rust:defs.bzl", "rust_clippy_test", "rustfmt_test")

exports_files([
    "Cargo.lock",
    "Cargo.toml",
])

rustfmt_test(
    name = "format_test",
    targets = [
        "//rust/crates/cluster-agent",
        "//rust/crates/control-plane",
        "//rust/crates/domain",
        "//rust/crates/entities",
        "//rust/crates/gateway",
        "//rust/crates/kubernetes",
        "//rust/crates/migration",
        "//rust/crates/operator",
        "//rust/crates/telemetry",
    ],
    transitive = True,
)

rust_clippy_test(
    name = "clippy_test",
    targets = [
        "//rust/crates/cluster-agent",
        "//rust/crates/control-plane",
        "//rust/crates/domain",
        "//rust/crates/entities",
        "//rust/crates/gateway",
        "//rust/crates/kubernetes",
        "//rust/crates/migration",
        "//rust/crates/operator",
        "//rust/crates/telemetry",
    ],
    transitive = True,
)
