load("@rules_python//python:defs.bzl", "py_binary", "py_library", "py_test")
load("@xscope_pypi//:requirements.bzl", "requirement")
load("@rules_python//python:pip.bzl", "compile_pip_requirements")
load("@xscope_telemetry_pypi//:requirements.bzl", telemetry_requirement = "requirement")

compile_pip_requirements(
    name = "telemetry_requirements",
    requirements_in = "telemetry.in",
    requirements_txt = "telemetry.lock",
    tags = ["manual"],
)

py_library(
    name = "runtime_lib",
    srcs = glob(["src/xscope_runtime/*.py"]),
    imports = ["src"],
    deps = [
        requirement("fastapi"),
        requirement("pydantic"),
        requirement("uvicorn"),
        telemetry_requirement("opentelemetry-sdk"),
        telemetry_requirement("opentelemetry-exporter-otlp-proto-http"),
        telemetry_requirement("prometheus-client"),
    ],
)

py_binary(
    name = "runtime",
    srcs = [
        "src/xscope_runtime/__init__.py",
        "src/xscope_runtime/main.py",
        "src/xscope_runtime/telemetry.py",
    ],
    imports = ["src"],
    main = "src/xscope_runtime/main.py",
    visibility = ["//visibility:public"],
    deps = [
        requirement("fastapi"),
        requirement("pydantic"),
        requirement("uvicorn"),
        telemetry_requirement("opentelemetry-sdk"),
        telemetry_requirement("opentelemetry-exporter-otlp-proto-http"),
        telemetry_requirement("prometheus-client"),
    ],
)

py_test(
    name = "runtime_test",
    srcs = ["tests/test_runtime.py"],
    imports = ["src"],
    main = "tests/test_runtime.py",
    deps = [
        ":runtime_lib",
        requirement("httpx"),
    ],
)
