// Code generated by controller-gen. DO NOT EDIT.
package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *ModelDeployment) DeepCopyInto(out *ModelDeployment) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = *in.Spec.DeepCopy()
	if in.Status.Conditions != nil {
		out.Status.Conditions = append([]metav1.Condition(nil), in.Status.Conditions...)
	}
}

func (in *ModelDeployment) DeepCopy() *ModelDeployment {
	if in == nil {
		return nil
	}
	out := new(ModelDeployment)
	in.DeepCopyInto(out)
	return out
}

func (in *ModelDeployment) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *ModelDeploymentList) DeepCopyInto(out *ModelDeploymentList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]ModelDeployment, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *ModelDeploymentList) DeepCopy() *ModelDeploymentList {
	if in == nil {
		return nil
	}
	out := new(ModelDeploymentList)
	in.DeepCopyInto(out)
	return out
}

func (in *ModelDeploymentList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *ModelDeploymentSpec) DeepCopy() *ModelDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(ModelDeploymentSpec)
	*out = *in
	out.Runtime.Arguments = append([]string(nil), in.Runtime.Arguments...)
	out.Resources = *in.Resources.DeepCopy()
	if in.Autoscaling != nil {
		out.Autoscaling = new(AutoscalingSpec)
		*out.Autoscaling = *in.Autoscaling
	}
	if in.Rollout != nil {
		out.Rollout = new(RolloutSpec)
		*out.Rollout = *in.Rollout
	}
	if in.NodeSelector != nil {
		out.NodeSelector = make(map[string]string, len(in.NodeSelector))
		for key, value := range in.NodeSelector {
			out.NodeSelector[key] = value
		}
	}
	out.Tolerations = append([]corev1.Toleration(nil), in.Tolerations...)
	return out
}
