apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../crds
  - ../../base
  - secrets.yaml
patches:
  - target:
      kind: ConfigMap
      name: xscope-config
    patch: |-
      - op: replace
        path: /data/XSCOPE_AUTO_JOIN_DEFAULT_TENANT
        value: "true"
  - target:
      kind: Service
      name: keycloak
    patch: |-
      - op: add
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30080
  - target:
      kind: Service
      name: console
    patch: |-
      - op: add
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30081
  - target:
      kind: Service
      name: gateway
    patch: |-
      - op: add
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30082
